[project]
name = "curate-code"
version = "0.1.0"
description = "Code implementation for CURATE (TMLR 2026), an automatic curriculum learning algorithm for reinforcement learning agents"
readme = "README.md"
requires-python = "==3.8.19"
dependencies = [
    "baselines",
    "box2d>=2.3.10",
    "cloudpickle>=1.2",
    "cma==2.7.0",
    "geopandas==0.9.0",
    "gin-config==0.1.2",
    "gym==0.15.7",
    "gym-minigrid==1.0.3",
    "lempel-ziv-complexity>=0.2.2",
    "matplotlib>=3.7.5",
    "networkx==2.5",
    "numpy==1.24.4",
    "pandas>=1.0.5",
    "procgen-curriculum",
    "pyglet>=1.5.0",
    "pyvirtualdisplay>=3.0",
    "scikit-learn==1.1.1",
    "seaborn>=0.13.2",
    "rl-utils",
    "tensorflow==2.7.4",
    "tensorflow-io-gcs-filesystem==0.34.0",
    "torch==2.4.1",
    "torchaudio==2.4.1",
    "torchvision==0.19.1",
    "tqdm>=4.46.1",
    "treelib==1.6.1",
]

[tool.uv.sources]
baselines = { path = "baselines-curate", editable = true }
rl-utils = { path = "rl-utils", editable = true }
procgen-curriculum = { path = "procgen-curriculum", editable = true }
